name: Run on a push into main

on:
  push:
    branches: [main]

permissions:
  contents: write

concurrency: # Only allow a single run at a time
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    needs: lint
    uses: ./.github/workflows/test.yml

  upload-package:
    needs: test
    uses: ./.github/workflows/upload-package.yml

  release:
    needs: upload-package
    uses: ./.github/workflows/release.yml
