name: Release tag pipeline

on:
  workflow_call:

permissions:
  contents: write

jobs:
  release-github:
    name: Upload to release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@main
        with:
          pixi-version: latest
          cache: true

      - name: Get the version
        id: get_version
        run: |
          TAG="$(pixi project version get)-compiler-$(pixi list | grep 'mojo-compiler' | awk '{print $2}')"
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Run the package command
        run: pixi run package

      - name: Upload package to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./build/mojo_datetime.mojopkg
          tag: ${{ steps.get_version.outputs.TAG }}
          overwrite: true
