name: Release tag pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-github:
    name: Upload to release
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - uses: actions/download-artifact@v4
        with:
          name: mojo_datetime-package

      - name: Upload package to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: mojo_datetime.mojopkg
          tag: ${{ steps.get_version.outputs.VERSION }}
          overwrite: true
