name: Run the testing suite

on:
    workflow_call:

jobs:
    test-linux:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Pixi
              uses: prefix-dev/setup-pixi@main
              with:
                  pixi-version: latest
                  cache: true
            - name: Run the test suite
              run: pixi run test

    test-macos:
        name: Run tests
        runs-on: macos-14
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Pixi
              uses: prefix-dev/setup-pixi@main
              with:
                  pixi-version: latest
                  cache: true
            - name: Run the test suite
              run: pixi run test